### ISSUE TITLE
Any prerequisites ?

### ISSUE THREAD

**Issue by Gtaverne** [Mazoise/NORMINETTE_VM_INSTALL#1]
Thank you for all what you're doing
I'm trying to install norminette 3.0 on my vm
On my VM, "norminette --version" was telling me 1.0.0 and 2.3.3 were installed. I didn't know how to remove them so I rm -rf .norminette

Any idea what should I reinstall now ?

When I'm following the steps you indicate, it gives me 
➜ norminette --version
zsh: aucun fichier ou dossier de ce type: /home/user42/.norminette/norminette.rb

**Comment by Mazoise** [comment]
You deleted the norminette V2 very drastically which wasn't necessary. You just need to comment the line in your ~/.zshrc which specifies the path to norminette V2 (Then "source ~/.zshrc" to take effect). The path to V3 will be found automatically if it was installed correctly.

**Comment by Gtaverne** [comment]
Many thanks for your help !
Doing your tuto step by step helped a great deal
